spring:
  application:
    name: API Rate Limiter

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    url: redis://${SPRING_REDIS_HOST:${spring.redis.host}}:${SPRING_REDIS_PORT:${spring.redis.port}}
    lettuce:
      shutdown-timeout: 100ms
      timeout: 10000ms
rate:
  limiter:
    clients:
      - clientId: client1
        windowSizeMs: 10000
        maxRequests: 5
      - clientId: client2
        windowSizeMs: 60000
        maxRequests: 10


# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: docker
  redis:
    host: redis
    port: 6379
    url: redis://redis:6379

---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6379